spring:
    application:
        name: "gatewayserver"
    config:
        import: "optional:configserver:http://localhost:8071/"
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: false
                    lower-case-service-id: true
            httpclient:
                connect-timeout: 1000
                response-timeout: 2s
    data:
        redis:
            connect-timeout: 2s
            host: localhost
            port: 6379
            timeout: 1s
            
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        gateway:
            enabled: true
    info:
        env:
            enabled: true

logging:
    level:
        com:
            learn:
                gatewayserver: DEBUG

info:
    app:
        name: "getwayserver"
        description: "Your Bank GateWayServer Application"
        version: "1.0.0"

resilience4j.circuitbreaker:
    configs:
        default:
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 2
            failureRateThreshold: 50
            waitDurationInOpenState: 10000