server:
    port: 8080
spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: ''
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create
        show-sql: true
    config:
        import:
            - "application_qa.yml"
            - "application_prod.yml"
    profiles:
        active:
            - "prod"

build:
    version: "1.0"
    
accounts:
    message: "Welcome to YourBank accounts related local APIs"
    contactDetails:
        name: "Golam Zaid - Developer"
        email: "golamzaid@yourbank.com"
    onCallSupport:
        - (555) 555-1234
        - (555) 523-1345

# --spring.profile.active=prod - command line arguments
# -Dspring.profile.active=prod - use to define VM ClassPaths
# SPRING_PROFILE_ACTIVE=prod - use to define